// swift-tools-version:5.10
import PackageDescription

// The public manifest. Generated by build-public-package.sh in
// paygent-net/rust-common; edit that template, never this file.
//
// The one difference from the manifest inside rust-common is the binary
// target: there it is a local path into a gitignored build directory, so a
// clone does not resolve. Here it is a URL and a checksum, which is what makes
// the package resolvable by anyone.
let package = Package(
    name: "PaygentSdk",
    // macOS is arm64 ONLY, and that is a constraint on YOUR target, not just on
    // ours. The xcframework carries an iOS device slice, two iOS simulator
    // slices and a macos-arm64 slice; there is no x86_64 macOS slice and there
    // will not be one, because an Intel Mac without a T2 has no usable Secure
    // Enclave to hold a key in. Xcode's default macOS ARCHS is universal, so a
    // macOS target that takes the default links against a slice that has no
    // x86_64 in it and fails with:
    //
    //     Undefined symbols for architecture x86_64: "_paygent_se_available"
    //
    // Pin `ARCHS = arm64` on whichever target links this package. In a
    // universal app that means putting the wallet in its own arm64-only target
    // -- an embedded helper, XPC service or app extension -- and pinning ARCHS
    // there; the enclosing app stays universal and never links this package.
    //
    // macCatalyst is still absent: no slice is built for it.
    platforms: [ .iOS(.v16), .macOS(.v13) ],
    products: [
        .library(name: "PaygentSdk", targets: ["PaygentSdk"]),
        .library(name: "PaygentMobileCore", targets: ["PaygentMobileCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "PaygentMobileCoreFFI",
            url: "https://github.com/paygent-net/paygent-swift/releases/download/0.7.0/PaygentMobileCoreFFI-0.7.0.xcframework.zip",
            checksum: "be068d963c286dd218ab7e2c423b8a1625b253bf6ebab8bd66b363b09e6eec89"
        ),
        .target(
            name: "PaygentMobileCore",
            dependencies: ["PaygentMobileCoreFFI"],
            path: "Sources/PaygentMobileCore"
        ),
        .target(
            name: "PaygentSdk",
            dependencies: ["PaygentMobileCore"],
            path: "Sources/PaygentSdk"
        ),
    ]
)
