// swift-tools-version:5.10
import PackageDescription

// The public manifest. Generated by build-public-package.sh in
// paygent-net/rust-common; edit that template, never this file.
//
// The one difference from the manifest inside rust-common is the binary
// target: there it is a local path into a gitignored build directory, so a
// clone does not resolve. Here it is a URL and a checksum, which is what makes
// the package resolvable by anyone.
let package = Package(
    name: "PaygentSdk",
    // iOS only, and deliberately not macOS or macCatalyst: the xcframework
    // carries an iOS device slice and two iOS simulator slices and nothing
    // else, so a target on any other platform resolves the manifest and then
    // fails at link time with no explanation.
    platforms: [ .iOS(.v16) ],
    products: [
        .library(name: "PaygentSdk", targets: ["PaygentSdk"]),
        .library(name: "PaygentMobileCore", targets: ["PaygentMobileCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "PaygentMobileCoreFFI",
            url: "https://github.com/paygent-net/paygent-swift/releases/download/0.3.0/PaygentMobileCoreFFI-0.3.0.xcframework.zip",
            checksum: "3f172d75dfc035adaf8b78716ae45926afebadc6dbd2abb99a03e28f55f49c1b"
        ),
        .target(
            name: "PaygentMobileCore",
            dependencies: ["PaygentMobileCoreFFI"],
            path: "Sources/PaygentMobileCore"
        ),
        .target(
            name: "PaygentSdk",
            dependencies: ["PaygentMobileCore"],
            path: "Sources/PaygentSdk"
        ),
    ]
)
