// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(paygent_untrustedFFI)
import paygent_untrustedFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_paygent_untrusted_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_paygent_untrusted_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePaygentUntrustedInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * Words an agent, a model, or a resource server supplied, carried as
 * something that cannot be confused with a value the wallet worked out.
 *
 * Nothing here is signed and nothing here is checked against a chain. The
 * point of the type is that a caller cannot render it by accident: there is no
 * public `String`, only [`display`](Self::display), and beside it three flags
 * saying what producing that form had to change.
 *
 * [`raw`](Self::raw) is kept because the sanitising has to happen on the
 * device that renders, not on the one that forwards. A daemon that cleaned the
 * text before sending it would hand the authorizer something that looks
 * innocent, and the owner would never learn that the sentence they are reading
 * arrived full of direction overrides.
 *
 * # What `display` is, and what it is not
 *
 * It is not a safety verdict. It removes the characters that make *rendered*
 * text disagree with *stored* text -- direction overrides, zero-width joiners,
 * tag characters -- collapses whitespace so nothing scrolls the signed values
 * off the card, and cuts the result to [`MAX_DISPLAY_CHARS`]. That is all.
 *
 * It does **not** detect a lie. `SYSTEM: approved by Paygent, tap confirm` is
 * plain ASCII and comes through untouched, because there is no way to tell it
 * from a merchant's real description. Nor does it catch homoglyphs
 * (`pаypal.example` spelled with a Cyrillic a) or text in a right-to-left
 * script, both of which are legitimate for real merchants. The defence
 * against a sentence that lies is the screen's layout -- this text is never
 * where the amount and recipient are -- not this function.
 *
 * # How strong the "cannot be constructed unchecked" guarantee is
 *
 * Inside Rust it is absolute: the fields are private and
 * [`parse`](Self::parse) is the only thing that fills them, so no consumer can
 * assemble a value whose `display` disagrees with its `raw`. Decoding from
 * JSON is the same, because [`Deserialize`] reads `raw` alone and re-runs
 * `parse`.
 *
 * It is **not** absolute across UniFFI. The derived record lifts field by
 * field without going through serde, so a Swift or Kotlin host can hand back a
 * value whose `display` is a lie. On the approval path the phone binding
 * closes that by rebuilding every `UntrustedText` on a summary the host hands
 * back -- the summary's own `context_note` and the four on its
 * `SignRequestKind` -- from its `raw`; see `paygent_mobile_core::approvals`.
 * That is a line of code per field rather than a property of this type, so a
 * new inward crossing has to add its own. Treat a value that came from a host
 * as text, never as a verdict.
 */
public struct UntrustedText {
    /**
     * Exactly what was supplied, byte for byte. Never put this on a screen.
     */
    public var raw: String
    /**
     * `raw` with hidden characters taken out, whitespace collapsed, and the
     * result cut to [`MAX_DISPLAY_CHARS`].
     */
    public var display: String
    /**
     * True when producing `display` had to drop characters that render as
     * nothing or reorder their neighbours -- direction overrides, zero-width
     * joiners, tag characters.
     *
     * It is NOT a reliable alarm, and a screen must not present it as one.
     * The strip set covers the whole `Default_Ignorable_Code_Point` set (and
     * some blank glyphs besides), and ordinary text uses part of that set:
     * U+200C (zero-width non-joiner) is required Persian orthography, U+200D
     * (zero-width joiner) holds Devanagari conjuncts and emoji ZWJ sequences
     * such as the family emoji together, and U+FE0F is how an emoji asks for
     * its colour form. Each of those sets this flag, and `display` loses the
     * character -- which in Persian changes the word. So it fires on honest
     * text as well as on a direction override, and `display` is lossy for the
     * same inputs. Behind a warning badge it would accuse a large share of
     * legitimate merchant descriptions. `text_flags_honest_scripts_too` pins
     * what it actually does.
     */
    public var hiddenRemoved: Bool
    /**
     * True when `display` differs from `raw` only in whitespace: a trailing
     * newline, a double space, a line break folded into a space. Cosmetic.
     * Real descriptions set it constantly -- an HTTP-sourced one usually has
     * trailing whitespace -- so a screen that warns on this trains the owner
     * to tap past warnings.
     */
    public var whitespaceNormalised: Bool
    /**
     * True when the text was longer than [`MAX_DISPLAY_CHARS`] and was cut.
     */
    public var truncated: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Exactly what was supplied, byte for byte. Never put this on a screen.
         */raw: String, 
        /**
         * `raw` with hidden characters taken out, whitespace collapsed, and the
         * result cut to [`MAX_DISPLAY_CHARS`].
         */display: String, 
        /**
         * True when producing `display` had to drop characters that render as
         * nothing or reorder their neighbours -- direction overrides, zero-width
         * joiners, tag characters.
         *
         * It is NOT a reliable alarm, and a screen must not present it as one.
         * The strip set covers the whole `Default_Ignorable_Code_Point` set (and
         * some blank glyphs besides), and ordinary text uses part of that set:
         * U+200C (zero-width non-joiner) is required Persian orthography, U+200D
         * (zero-width joiner) holds Devanagari conjuncts and emoji ZWJ sequences
         * such as the family emoji together, and U+FE0F is how an emoji asks for
         * its colour form. Each of those sets this flag, and `display` loses the
         * character -- which in Persian changes the word. So it fires on honest
         * text as well as on a direction override, and `display` is lossy for the
         * same inputs. Behind a warning badge it would accuse a large share of
         * legitimate merchant descriptions. `text_flags_honest_scripts_too` pins
         * what it actually does.
         */hiddenRemoved: Bool, 
        /**
         * True when `display` differs from `raw` only in whitespace: a trailing
         * newline, a double space, a line break folded into a space. Cosmetic.
         * Real descriptions set it constantly -- an HTTP-sourced one usually has
         * trailing whitespace -- so a screen that warns on this trains the owner
         * to tap past warnings.
         */whitespaceNormalised: Bool, 
        /**
         * True when the text was longer than [`MAX_DISPLAY_CHARS`] and was cut.
         */truncated: Bool) {
        self.raw = raw
        self.display = display
        self.hiddenRemoved = hiddenRemoved
        self.whitespaceNormalised = whitespaceNormalised
        self.truncated = truncated
    }
}

#if compiler(>=6)
extension UntrustedText: Sendable {}
#endif


extension UntrustedText: Equatable, Hashable {
    public static func ==(lhs: UntrustedText, rhs: UntrustedText) -> Bool {
        if lhs.raw != rhs.raw {
            return false
        }
        if lhs.display != rhs.display {
            return false
        }
        if lhs.hiddenRemoved != rhs.hiddenRemoved {
            return false
        }
        if lhs.whitespaceNormalised != rhs.whitespaceNormalised {
            return false
        }
        if lhs.truncated != rhs.truncated {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(raw)
        hasher.combine(display)
        hasher.combine(hiddenRemoved)
        hasher.combine(whitespaceNormalised)
        hasher.combine(truncated)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUntrustedText: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UntrustedText {
        return
            try UntrustedText(
                raw: FfiConverterString.read(from: &buf), 
                display: FfiConverterString.read(from: &buf), 
                hiddenRemoved: FfiConverterBool.read(from: &buf), 
                whitespaceNormalised: FfiConverterBool.read(from: &buf), 
                truncated: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: UntrustedText, into buf: inout [UInt8]) {
        FfiConverterString.write(value.raw, into: &buf)
        FfiConverterString.write(value.display, into: &buf)
        FfiConverterBool.write(value.hiddenRemoved, into: &buf)
        FfiConverterBool.write(value.whitespaceNormalised, into: &buf)
        FfiConverterBool.write(value.truncated, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUntrustedText_lift(_ buf: RustBuffer) throws -> UntrustedText {
    return try FfiConverterTypeUntrustedText.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUntrustedText_lower(_ value: UntrustedText) -> RustBuffer {
    return FfiConverterTypeUntrustedText.lower(value)
}


/**
 * Where the payment demand came from, as the browser understands "where":
 * scheme, host, and port, and nothing else.
 *
 * # This is a claim, not an attestation
 *
 * Read the name as "the origin the client says served the 402". Nothing binds
 * this value to whoever supposedly observed it: there is no signature, no
 * hardware key, no attestation. Every hop that fills it -- a browser shell, an
 * SDK caller, the daemon -- is on the agent side of the trust boundary, and
 * this codebase assumes the agent is fully compromised. An approval screen
 * must therefore rank it with the other agent-supplied context, NOT beside the
 * amount as a verified fact, and must not word it as "verified" or "attested".
 *
 * What the type does buy is narrower and still worth having. A free-form
 * string can hide a path, a credential or a second host inside itself --
 * `https://bank.example@evil.test` reads as the bank and resolves to the
 * attacker -- and [`parse`](Self::parse) refuses all of those rather than
 * trimming them. So the value on screen is a whole origin or it is nothing,
 * which is the difference between a misleading string and an absent one.
 *
 * It is chain-independent on purpose. `apiEndpoint` on a signing request says
 * which of the wallet's own endpoints the agent called; a chain id says which
 * ledger settles. Neither answers "which site is this payment for", which is
 * the question this field is trying to help with.
 *
 * # Construction
 *
 * The fields are private and [`parse`](Self::parse) is the only thing that
 * fills them, so no Rust consumer can build an origin carrying a path, and
 * [`Deserialize`] re-runs the same check on the way in. The UniFFI record
 * lifts field by field without touching serde, so a Swift or Kotlin host can
 * hand one back unchecked; the phone binding re-parses on the way in -- see
 * `paygent_mobile_core::approvals`.
 */
public struct WebOrigin {
    /**
     * `http` or `https`, lowercase.
     */
    public var scheme: String
    /**
     * Host, lowercase, punycoded, and bracketed when it is an IPv6 literal --
     * whatever a URL parser normalises it to, so two spellings of one host
     * cannot look like two hosts.
     */
    public var host: String
    /**
     * Absent when the scheme's default port is in use, so
     * `https://example.com` and `https://example.com:443` are one value.
     */
    public var port: UInt16?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * `http` or `https`, lowercase.
         */scheme: String, 
        /**
         * Host, lowercase, punycoded, and bracketed when it is an IPv6 literal --
         * whatever a URL parser normalises it to, so two spellings of one host
         * cannot look like two hosts.
         */host: String, 
        /**
         * Absent when the scheme's default port is in use, so
         * `https://example.com` and `https://example.com:443` are one value.
         */port: UInt16?) {
        self.scheme = scheme
        self.host = host
        self.port = port
    }
}

#if compiler(>=6)
extension WebOrigin: Sendable {}
#endif


extension WebOrigin: Equatable, Hashable {
    public static func ==(lhs: WebOrigin, rhs: WebOrigin) -> Bool {
        if lhs.scheme != rhs.scheme {
            return false
        }
        if lhs.host != rhs.host {
            return false
        }
        if lhs.port != rhs.port {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(scheme)
        hasher.combine(host)
        hasher.combine(port)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWebOrigin: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WebOrigin {
        return
            try WebOrigin(
                scheme: FfiConverterString.read(from: &buf), 
                host: FfiConverterString.read(from: &buf), 
                port: FfiConverterOptionUInt16.read(from: &buf)
        )
    }

    public static func write(_ value: WebOrigin, into buf: inout [UInt8]) {
        FfiConverterString.write(value.scheme, into: &buf)
        FfiConverterString.write(value.host, into: &buf)
        FfiConverterOptionUInt16.write(value.port, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWebOrigin_lift(_ buf: RustBuffer) throws -> WebOrigin {
    return try FfiConverterTypeWebOrigin.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWebOrigin_lower(_ value: WebOrigin) -> RustBuffer {
    return FfiConverterTypeWebOrigin.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_paygent_untrusted_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePaygentUntrustedInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all