// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(paygent_policyFFI)
import paygent_policyFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_paygent_policy_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_paygent_policy_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePaygentPolicyInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct PolicyDecision {
    public var action: PolicyAction
    public var signingPath: SigningPath?
    public var reason: String?
    /**
     * Why the owner is being asked, as a value a screen can branch on.
     * Present exactly when `action` is `Authorize` for a stated reason;
     * `reason` stays the log-friendly sentence.
     */
    public var escalation: EscalationReason?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(action: PolicyAction, signingPath: SigningPath?, reason: String?, 
        /**
         * Why the owner is being asked, as a value a screen can branch on.
         * Present exactly when `action` is `Authorize` for a stated reason;
         * `reason` stays the log-friendly sentence.
         */escalation: EscalationReason?) {
        self.action = action
        self.signingPath = signingPath
        self.reason = reason
        self.escalation = escalation
    }
}

#if compiler(>=6)
extension PolicyDecision: Sendable {}
#endif


extension PolicyDecision: Equatable, Hashable {
    public static func ==(lhs: PolicyDecision, rhs: PolicyDecision) -> Bool {
        if lhs.action != rhs.action {
            return false
        }
        if lhs.signingPath != rhs.signingPath {
            return false
        }
        if lhs.reason != rhs.reason {
            return false
        }
        if lhs.escalation != rhs.escalation {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(action)
        hasher.combine(signingPath)
        hasher.combine(reason)
        hasher.combine(escalation)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePolicyDecision: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PolicyDecision {
        return
            try PolicyDecision(
                action: FfiConverterTypePolicyAction.read(from: &buf), 
                signingPath: FfiConverterOptionTypeSigningPath.read(from: &buf), 
                reason: FfiConverterOptionString.read(from: &buf), 
                escalation: FfiConverterOptionTypeEscalationReason.read(from: &buf)
        )
    }

    public static func write(_ value: PolicyDecision, into buf: inout [UInt8]) {
        FfiConverterTypePolicyAction.write(value.action, into: &buf)
        FfiConverterOptionTypeSigningPath.write(value.signingPath, into: &buf)
        FfiConverterOptionString.write(value.reason, into: &buf)
        FfiConverterOptionTypeEscalationReason.write(value.escalation, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePolicyDecision_lift(_ buf: RustBuffer) throws -> PolicyDecision {
    return try FfiConverterTypePolicyDecision.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePolicyDecision_lower(_ value: PolicyDecision) -> RustBuffer {
    return FfiConverterTypePolicyDecision.lower(value)
}


/**
 * Sans-IO description of what a write command is asking to do.
 *
 * The policy engine consumes this together with `CommandContext` to
 * decide silent / escalate / deny. Read-only commands skip the policy
 * engine entirely (decided by `auth_level == None`).
 */
public struct PolicyIntent {
    public var commandName: String
    public var chainId: UInt64?
    public var wallet: String?
    /**
     * Who receives the value: the EVM address or Solana account the payment
     * is addressed to.
     *
     * This is NOT the call target. For an ERC-20 payment the transaction's
     * `to` is the token contract, and the payee is a word inside the
     * calldata -- which is why the guard's on-chain `allowedTargets` list
     * does not bound it, and why this field has to be carried separately for
     * the engine to have a payee at all.
     *
     * `None` for commands that pay nobody (`pair_device`, `sign_message`).
     * On a third-party transfer `None` escalates: a transfer that does not
     * say who it pays cannot have its payee checked, and an intent the
     * caller under-filled must not be cheaper to get past than one it
     * filled in.
     */
    public var recipient: String?
    /**
     * Token contract address (`0x0000...0000` for native ETH). Lower-cased.
     */
    public var token: String?
    /**
     * Amount the command wants to spend. `None` when the command
     * doesn't carry an amount (e.g. `pair_device`, `sign_message`).
     */
    public var amount: IntentAmount?
    /**
     * CAIP-2 network id the command targets, when known
     * (e.g. `"solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1"` for Solana
     * devnet, `"eip155:8453"` for Base). The decision engine dispatches
     * on the chain *family* parsed from this: a `"solana:"` prefix routes
     * to the Solana limits reader; anything else uses the EVM path keyed
     * on `chain_id`. `None` keeps the legacy EVM-only behaviour.
     */
    public var network: String?
    /**
     * SPL token mint (base58) for Solana intents. The Solana guard /
     * agent allowance accounts are keyed per-mint, so the limits reader
     * needs this to find the right vault. Ignored on the EVM path.
     */
    public var mint: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(commandName: String, chainId: UInt64?, wallet: String?, 
        /**
         * Who receives the value: the EVM address or Solana account the payment
         * is addressed to.
         *
         * This is NOT the call target. For an ERC-20 payment the transaction's
         * `to` is the token contract, and the payee is a word inside the
         * calldata -- which is why the guard's on-chain `allowedTargets` list
         * does not bound it, and why this field has to be carried separately for
         * the engine to have a payee at all.
         *
         * `None` for commands that pay nobody (`pair_device`, `sign_message`).
         * On a third-party transfer `None` escalates: a transfer that does not
         * say who it pays cannot have its payee checked, and an intent the
         * caller under-filled must not be cheaper to get past than one it
         * filled in.
         */recipient: String?, 
        /**
         * Token contract address (`0x0000...0000` for native ETH). Lower-cased.
         */token: String?, 
        /**
         * Amount the command wants to spend. `None` when the command
         * doesn't carry an amount (e.g. `pair_device`, `sign_message`).
         */amount: IntentAmount?, 
        /**
         * CAIP-2 network id the command targets, when known
         * (e.g. `"solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1"` for Solana
         * devnet, `"eip155:8453"` for Base). The decision engine dispatches
         * on the chain *family* parsed from this: a `"solana:"` prefix routes
         * to the Solana limits reader; anything else uses the EVM path keyed
         * on `chain_id`. `None` keeps the legacy EVM-only behaviour.
         */network: String?, 
        /**
         * SPL token mint (base58) for Solana intents. The Solana guard /
         * agent allowance accounts are keyed per-mint, so the limits reader
         * needs this to find the right vault. Ignored on the EVM path.
         */mint: String?) {
        self.commandName = commandName
        self.chainId = chainId
        self.wallet = wallet
        self.recipient = recipient
        self.token = token
        self.amount = amount
        self.network = network
        self.mint = mint
    }
}

#if compiler(>=6)
extension PolicyIntent: Sendable {}
#endif


extension PolicyIntent: Equatable, Hashable {
    public static func ==(lhs: PolicyIntent, rhs: PolicyIntent) -> Bool {
        if lhs.commandName != rhs.commandName {
            return false
        }
        if lhs.chainId != rhs.chainId {
            return false
        }
        if lhs.wallet != rhs.wallet {
            return false
        }
        if lhs.recipient != rhs.recipient {
            return false
        }
        if lhs.token != rhs.token {
            return false
        }
        if lhs.amount != rhs.amount {
            return false
        }
        if lhs.network != rhs.network {
            return false
        }
        if lhs.mint != rhs.mint {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(commandName)
        hasher.combine(chainId)
        hasher.combine(wallet)
        hasher.combine(recipient)
        hasher.combine(token)
        hasher.combine(amount)
        hasher.combine(network)
        hasher.combine(mint)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePolicyIntent: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PolicyIntent {
        return
            try PolicyIntent(
                commandName: FfiConverterString.read(from: &buf), 
                chainId: FfiConverterOptionUInt64.read(from: &buf), 
                wallet: FfiConverterOptionString.read(from: &buf), 
                recipient: FfiConverterOptionString.read(from: &buf), 
                token: FfiConverterOptionString.read(from: &buf), 
                amount: FfiConverterOptionTypeIntentAmount.read(from: &buf), 
                network: FfiConverterOptionString.read(from: &buf), 
                mint: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: PolicyIntent, into buf: inout [UInt8]) {
        FfiConverterString.write(value.commandName, into: &buf)
        FfiConverterOptionUInt64.write(value.chainId, into: &buf)
        FfiConverterOptionString.write(value.wallet, into: &buf)
        FfiConverterOptionString.write(value.recipient, into: &buf)
        FfiConverterOptionString.write(value.token, into: &buf)
        FfiConverterOptionTypeIntentAmount.write(value.amount, into: &buf)
        FfiConverterOptionString.write(value.network, into: &buf)
        FfiConverterOptionString.write(value.mint, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePolicyIntent_lift(_ buf: RustBuffer) throws -> PolicyIntent {
    return try FfiConverterTypePolicyIntent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePolicyIntent_lower(_ value: PolicyIntent) -> RustBuffer {
    return FfiConverterTypePolicyIntent.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum EscalationReason {
    
    case overPerTx(amount: String, maxPerTx: String
    )
    case overDaily(amount: String, remaining: String
    )
    case noLimit
    case thirdPartyPayee
    case other(detail: String
    )
}


#if compiler(>=6)
extension EscalationReason: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEscalationReason: FfiConverterRustBuffer {
    typealias SwiftType = EscalationReason

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EscalationReason {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .overPerTx(amount: try FfiConverterString.read(from: &buf), maxPerTx: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .overDaily(amount: try FfiConverterString.read(from: &buf), remaining: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .noLimit
        
        case 4: return .thirdPartyPayee
        
        case 5: return .other(detail: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EscalationReason, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .overPerTx(amount,maxPerTx):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(amount, into: &buf)
            FfiConverterString.write(maxPerTx, into: &buf)
            
        
        case let .overDaily(amount,remaining):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(amount, into: &buf)
            FfiConverterString.write(remaining, into: &buf)
            
        
        case .noLimit:
            writeInt(&buf, Int32(3))
        
        
        case .thirdPartyPayee:
            writeInt(&buf, Int32(4))
        
        
        case let .other(detail):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEscalationReason_lift(_ buf: RustBuffer) throws -> EscalationReason {
    return try FfiConverterTypeEscalationReason.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEscalationReason_lower(_ value: EscalationReason) -> RustBuffer {
    return FfiConverterTypeEscalationReason.lower(value)
}


extension EscalationReason: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Amount carried in a `PolicyIntent`. The wire layer (REST / MCP)
 * passes user-friendly decimal strings (`"0.1"` ETH); the policy
 * engine resolves these to base units against the token's `decimals()`
 * view. Some legacy call sites already have a `U256` in base units;
 * those use [`IntentAmount::BaseUnits`] to skip the resolver.
 */

public enum IntentAmount {
    
    /**
     * User-facing decimal string in token units (e.g. `"0.1"`).
     */
    case decimal(String
    )
    /**
     * Already in the token's smallest unit. No resolver lookup needed.
     */
    case baseUnits(U256
    )
}


#if compiler(>=6)
extension IntentAmount: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIntentAmount: FfiConverterRustBuffer {
    typealias SwiftType = IntentAmount

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IntentAmount {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .decimal(try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .baseUnits(try FfiConverterTypeU256.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: IntentAmount, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .decimal(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .baseUnits(v1):
            writeInt(&buf, Int32(2))
            FfiConverterTypeU256.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIntentAmount_lift(_ buf: RustBuffer) throws -> IntentAmount {
    return try FfiConverterTypeIntentAmount.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIntentAmount_lower(_ value: IntentAmount) -> RustBuffer {
    return FfiConverterTypeIntentAmount.lower(value)
}


extension IntentAmount: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum PolicyAction {
    
    /**
     * Execute silently with the hardware-bound P256 key.
     */
    case silent
    /**
     * Escalate to the mobile authorizer (deferred-mode return).
     */
    case authorize
    /**
     * Refuse.
     */
    case deny
}


#if compiler(>=6)
extension PolicyAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePolicyAction: FfiConverterRustBuffer {
    typealias SwiftType = PolicyAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PolicyAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .silent
        
        case 2: return .authorize
        
        case 3: return .deny
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PolicyAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .silent:
            writeInt(&buf, Int32(1))
        
        
        case .authorize:
            writeInt(&buf, Int32(2))
        
        
        case .deny:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePolicyAction_lift(_ buf: RustBuffer) throws -> PolicyAction {
    return try FfiConverterTypePolicyAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePolicyAction_lower(_ value: PolicyAction) -> RustBuffer {
    return FfiConverterTypePolicyAction.lower(value)
}


extension PolicyAction: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SigningPath {
    
    /**
     * Hardware-bound P256 (Secure Enclave / TPM).
     */
    case p256
    /**
     * Mobile WebAuthn assertion via relay.
     */
    case webauthn
    /**
     * Mobile relay signing (containerised, hardware unavailable).
     */
    case relay
}


#if compiler(>=6)
extension SigningPath: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSigningPath: FfiConverterRustBuffer {
    typealias SwiftType = SigningPath

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SigningPath {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .p256
        
        case 2: return .webauthn
        
        case 3: return .relay
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SigningPath, into buf: inout [UInt8]) {
        switch value {
        
        
        case .p256:
            writeInt(&buf, Int32(1))
        
        
        case .webauthn:
            writeInt(&buf, Int32(2))
        
        
        case .relay:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSigningPath_lift(_ buf: RustBuffer) throws -> SigningPath {
    return try FfiConverterTypeSigningPath.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSigningPath_lower(_ value: SigningPath) -> RustBuffer {
    return FfiConverterTypeSigningPath.lower(value)
}


extension SigningPath: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeEscalationReason: FfiConverterRustBuffer {
    typealias SwiftType = EscalationReason?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeEscalationReason.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeEscalationReason.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeIntentAmount: FfiConverterRustBuffer {
    typealias SwiftType = IntentAmount?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeIntentAmount.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeIntentAmount.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSigningPath: FfiConverterRustBuffer {
    typealias SwiftType = SigningPath?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSigningPath.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSigningPath.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_paygent_policy_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }

    uniffiEnsurePaygentAgentCoreInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePaygentPolicyInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all